apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy-backend
  template:
    metadata:
      labels:
        app: paymybuddy-backend
    spec:
      containers:
      - name: paymybuddy-backend
        image: baaptistee/paymybuddy-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://paymybuddy-db:3306/db_paymybuddy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "paymybuddy_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "paymybuddy"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.MySQL8Dialect"
